version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:swc'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - node-net

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb-data/data
    networks:
      - node-net

volumes:
  mongodb-data:

networks:
  node-net:
