version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    depends_on:
      - mongo
      - redis
    links:
      - mongo
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:swc'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - node-net

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb-data/data
    networks:
      - node-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    networks:
      - node-net
    volumes:
      - cache:/data

volumes:
  mongodb-data:
  cache:

networks:
  node-net:
